/*
-- Query: SELECT * FROM funrestdb.tbl_project
LIMIT 0, 50000

-- Date: 2024-06-13 10:29
*/
INSERT INTO `` (`proCode`,`fileAttached`,`proCategory`,`proDate`,`proEndDate`,`proGoalAmount`,`proName`,`proNotifyCnt`,`proPaidCnt`,`proPrice`,`proScript`,`proStartDate`,`proStatus`,`sellerDetail`,`sellerName`,`subFileAttached`,`userId`) VALUES (964,1,'movie',NULL,'','124,214,412','main1',0,123,'123,213','main1','',0,'main1','main1',1,'rbghrla@naver.com');
INSERT INTO `` (`proCode`,`fileAttached`,`proCategory`,`proDate`,`proEndDate`,`proGoalAmount`,`proName`,`proNotifyCnt`,`proPaidCnt`,`proPrice`,`proScript`,`proStartDate`,`proStatus`,`sellerDetail`,`sellerName`,`subFileAttached`,`userId`) VALUES (965,1,'book',NULL,'','12,312,312,321','main2',0,345,'21,321,414','main2','',0,'main2','main2',1,'rbghrla@naver.com');
INSERT INTO `` (`proCode`,`fileAttached`,`proCategory`,`proDate`,`proEndDate`,`proGoalAmount`,`proName`,`proNotifyCnt`,`proPaidCnt`,`proPrice`,`proScript`,`proStartDate`,`proStatus`,`sellerDetail`,`sellerName`,`subFileAttached`,`userId`) VALUES (966,1,'musical',NULL,'','12,312,312,321','main3',0,5654,'21,321,414','main3','',0,'main3','main3',1,'rbghrla@naver.com');
INSERT INTO `` (`proCode`,`fileAttached`,`proCategory`,`proDate`,`proEndDate`,`proGoalAmount`,`proName`,`proNotifyCnt`,`proPaidCnt`,`proPrice`,`proScript`,`proStartDate`,`proStatus`,`sellerDetail`,`sellerName`,`subFileAttached`,`userId`) VALUES (967,1,'musical',NULL,'','12,312,312,321','main4',0,765,'12,331','main4','',0,'main4','main4',1,'rbghrla@naver.com');
INSERT INTO `` (`proCode`,`fileAttached`,`proCategory`,`proDate`,`proEndDate`,`proGoalAmount`,`proName`,`proNotifyCnt`,`proPaidCnt`,`proPrice`,`proScript`,`proStartDate`,`proStatus`,`sellerDetail`,`sellerName`,`subFileAttached`,`userId`) VALUES (968,1,'book',NULL,'','12,312,312,321','main5',0,465,'21,321,414','main5','',0,'main5','main5',1,'rbghrla@naver.com');
INSERT INTO `` (`proCode`,`fileAttached`,`proCategory`,`proDate`,`proEndDate`,`proGoalAmount`,`proName`,`proNotifyCnt`,`proPaidCnt`,`proPrice`,`proScript`,`proStartDate`,`proStatus`,`sellerDetail`,`sellerName`,`subFileAttached`,`userId`) VALUES (969,1,'musical',NULL,'','12,312,312,321','main6',0,56,'12,331','main6','',0,'main6','main6',1,'rbghrla@naver.com');
INSERT INTO `` (`proCode`,`fileAttached`,`proCategory`,`proDate`,`proEndDate`,`proGoalAmount`,`proName`,`proNotifyCnt`,`proPaidCnt`,`proPrice`,`proScript`,`proStartDate`,`proStatus`,`sellerDetail`,`sellerName`,`subFileAttached`,`userId`) VALUES (970,1,'movie',NULL,'','132,123,132,312,321','main7',0,345,'12,331','main7','',0,'main7','main7',1,'rbghrla@naver.com');
INSERT INTO `` (`proCode`,`fileAttached`,`proCategory`,`proDate`,`proEndDate`,`proGoalAmount`,`proName`,`proNotifyCnt`,`proPaidCnt`,`proPrice`,`proScript`,`proStartDate`,`proStatus`,`sellerDetail`,`sellerName`,`subFileAttached`,`userId`) VALUES (971,1,'musical',NULL,'','123,123','main8',0,767,'133,131,221','main8','',0,'main8','main8',1,'rbghrla@naver.com');
INSERT INTO `` (`proCode`,`fileAttached`,`proCategory`,`proDate`,`proEndDate`,`proGoalAmount`,`proName`,`proNotifyCnt`,`proPaidCnt`,`proPrice`,`proScript`,`proStartDate`,`proStatus`,`sellerDetail`,`sellerName`,`subFileAttached`,`userId`) VALUES (972,1,'movie',NULL,'','123,123','main9',0,3,'21,321,414','main9','',0,'main9','main9',1,'rbghrla@naver.com');
INSERT INTO `` (`proCode`,`fileAttached`,`proCategory`,`proDate`,`proEndDate`,`proGoalAmount`,`proName`,`proNotifyCnt`,`proPaidCnt`,`proPrice`,`proScript`,`proStartDate`,`proStatus`,`sellerDetail`,`sellerName`,`subFileAttached`,`userId`) VALUES (973,1,'musical',NULL,'','12,312,312,321','main10',0,345,'12,331','main10','',0,'main10','main10',1,'rbghrla@naver.com');
INSERT INTO `` (`proCode`,`fileAttached`,`proCategory`,`proDate`,`proEndDate`,`proGoalAmount`,`proName`,`proNotifyCnt`,`proPaidCnt`,`proPrice`,`proScript`,`proStartDate`,`proStatus`,`sellerDetail`,`sellerName`,`subFileAttached`,`userId`) VALUES (974,1,'movie',NULL,'','12,312,312,321','main11',0,2321,'133,131,221','main11','',0,'main11','main11',1,'rbghrla@naver.com');
INSERT INTO `` (`proCode`,`fileAttached`,`proCategory`,`proDate`,`proEndDate`,`proGoalAmount`,`proName`,`proNotifyCnt`,`proPaidCnt`,`proPrice`,`proScript`,`proStartDate`,`proStatus`,`sellerDetail`,`sellerName`,`subFileAttached`,`userId`) VALUES (975,1,'musical',NULL,'','123,213','main12',0,423,'1,233','main12','',0,'main12','main12',1,'rbghrla@naver.com');
